
//Admin Request ------------------------------------------------
export const ADMIN_COLLECTOR_REQUEST = "ADMIN_COLLECTOR_REQUEST";
export const ADMIN_COLLECTOR_SUCCESS = "ADMIN_COLLECTOR_SUCCESS";
export const ADMIN_COLLECTOR_FAIL = "ADMIN_COLLECTOR_FAIL";
//Admin Request ------------------------------------------------

export const COLLECTOR_DETAILS_REQUEST = "COLLECTOR_DETAILS_REQUEST";
export const COLLECTOR_DETAILS_SUCCESS = "COLLECTOR_DETAILS_SUCCESS";
export const COLLECTOR_DETAILS_FAIL = "COLLECTOR_DETAILS_FAIL";

// Admin side COLLECTOR <---------Create
export const NEW_COLLECTOR_REQUEST = "NEW_COLLECTOR_REQUEST";
export const NEW_COLLECTOR_SUCCESS = "NEW_COLLECTOR_SUCCESS";
export const NEW_COLLECTOR_RESET = "NEW_COLLECTOR_RESET";
export const NEW_COLLECTOR_FAIL = "NEW_COLLECTOR_FAIL";


// Admin side DelProd <---------Create
export const DELETE_COLLECTOR_REQUEST = "DELETE_COLLECTOR_REQUEST";
export const DELETE_COLLECTOR_SUCCESS = "DELETE_COLLECTOR_SUCCESS";
export const DELETE_COLLECTOR_RESET = "DELETE_COLLECTOR_RESET";
export const DELETE_COLLECTOR_FAIL = "DELETE_COLLECTOR_FAIL";

export const UPDATE_COLLECTOR_REQUEST = "UPDATE_COLLECTOR_REQUEST";
export const UPDATE_COLLECTOR_SUCCESS = "UPDATE_COLLECTOR_SUCCESS";
export const UPDATE_COLLECTOR_RESET = "UPDATE_COLLECTOR_RESET";
export const UPDATE_COLLECTOR_FAIL = "UPDATE_COLLECTOR_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";